#!/data/data/com.termux/files/usr/bin/bash
export DISPLAY=:0
termux-x11 :0 &
sleep 3
am start --user 0 -n com.termux.x11/.MainActivity
proot-distro login ubuntu -- bash -c "openbox-session & sleep 3 && chromium-browser --disable-gpu --single-process &"#!/data/data/com.termux/files/usr/bin/bash
export DISPLAY=:0
termux-x11 :0 &
sleep 3
am start --user 0 -n com.termux.x11/.MainActivity
proot-distro login ubuntu -- bash -c "openbox-session & sleep 3 && chromium -- disable-gpu --single-process &"
